### ISSUE TITLE
Highlight verse in Reader

### ISSUE THREAD

**Issue by Correct-Syntax** [BibleNotify/BibleNotifyDesktop#5]
**Description**

When the notification is clicked, the verse should be highlighted in the reader (otherwise you may forget what the verse was when you click the notification)

**Steps to Reproduce**

N/A

**Additional Information**

- Commit: The latest
- OS: N/A

**Comment by Correct-Syntax** [comment]
I think just bolding the verse is good enough. Unless you have another thought?

**Comment by iwoithe** [comment]
Unless I am mistaken, I think the only way to do that is to edit the JSON files, correct?

**Comment by Correct-Syntax** [comment]
The way I think we could do it is:

1) get the json chapter text content
2) using regex (or just find and replace) match the current verse. Maybe look at my Bibleengine code for ideas on how to do that.
3) add <b> tags around that verse
4) insert/replace that verse in the chapter text with the bolded verse
5) display the new text content

There will also need to be a conditional so that if the chapter is being randomly selected (not via a notification click), that no verse is highlighted (bolded).
